from selenium.webdriver.common.by import By

class Locators_feed:

    constructor = (By.XPATH, ".//p[text()='Конструктор']")
    main_page = (By.XPATH, ".//h1[text()='Соберите бургер']")
    order_feed = (By.XPATH, ".//p[text()='Лента Заказов']")
    order_feed_activ = (By.XPATH, ".//h1[text()='Лента Заказов']")
    card_order = (By.XPATH, ".//p[text()='Cостав']")
    order_in_account = (By.XPATH, ".//p[@class='text text_type_digits-default']")
    order_in_account1 = (By.XPATH, ".//h2[@class='text text_type_main-medium mb-2']")
    order_in_account2 = (By.XPATH, ".//h2[text()='Флюоресцентный бургер']")
    order_in_feed = (By.XPATH, "(//div[contains(@class, 'OrderHistory_dataBox__1mkxK')])[1]")
    order_list = (By.XPATH, ".//ul[@class='OrderFeed_list__OLh59']")
    sous = (By.XPATH, ".//img[@alt='Соус Spicy-X']")
    ingredient = (By.XPATH, ".//p[text()='Флюоресцентная булка R2-D3']")
    basket = (By.XPATH, ".//div[@class='constructor-element constructor-element_pos_top']")
    count = (By.XPATH, ".//p[@class='text text_type_digits-medium mr-3']")
    active_order = (By.XPATH, ".//p[text()='Ваш заказ начали готовить']")
    place_order = (By.XPATH, ".//button[text()='Оформить заказ']")
    personal_account = (By.XPATH, ".//p[text()='Личный Кабинет']")
    entrance = (By.XPATH, ".//h2[text()='Вход']")
    history_orders1 = (By.XPATH, ".//a[text()='История заказов']")
    history_orders = (By.XPATH, ".//a[@class='Account_link__2ETsJ text text_type_main-medium text_color_inactive']")
    counter = (By.XPATH, ".//p[text()='Выполнено за все время:']/following-sibling::p")
    counter_now = (By.XPATH, ".//p[text()='Выполнено за сегодня:']/following-sibling::p")
    at_work = (By.XPATH, ".//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']")
    final = (By.XPATH, ".//ul[@class='OrderFeed_orderList__cBvyi']")
    at_work2 = (By.XPATH, '//*[contains(@class,"orderListReady")]//li[contains(@class,"digits-default")]')